In [3]:
# import pandas 
import pandas as pd

In [7]:
#import data and store data frame
pd.read_csv("ems20_1st_6months_excerpt.csv")

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [9]:
# store into data frame 
ems2020_excerpt_df = pd.read_csv("ems20_1st_6months_excerpt.csv")

In [13]:
# call the first 10 rows 
ems2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [15]:
# call the last 5 rows 
ems2020_excerpt_df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [17]:
# call random 20 rows
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
3125,200332465,2020-02-02 14:57:42,UNKNOW,4,UNKNOW,4,02/02/2020 02:57:57 PM,Y,15,02/02/2020 02:58:07 PM,...,90.0,34.0,301.0,14.0,7.0,N,N,N,N,chunk166.csv
11097,201433029,2020-05-22 19:21:51,UNKNOW,4,SICK,6,05/22/2020 07:23:42 PM,Y,111,05/22/2020 07:23:54 PM,...,115.0,25.0,403.0,30.0,14.0,N,N,N,N,chunk171.csv
11981,200064050,2020-01-06 20:05:39,SICK,6,SICK,6,01/06/2020 08:07:16 PM,Y,97,01/06/2020 08:07:32 PM,...,113.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk165.csv
1932,201533847,2020-06-01 22:16:57,INJURY,5,INJURY,5,06/01/2020 10:18:16 PM,Y,79,06/01/2020 10:18:28 PM,...,46.0,15.0,205.0,10.0,15.0,N,N,N,N,chunk171.csv
2658,201123708,2020-04-21 21:26:07,EDP,7,EDP,7,04/21/2020 09:26:19 PM,Y,12,04/21/2020 09:26:31 PM,...,49.0,15.0,209.0,11.0,15.0,N,N,N,N,chunk170.csv
9149,201410635,2020-05-20 05:20:53,UNKNOW,4,UNKNOW,4,05/20/2020 05:21:04 AM,Y,11,05/20/2020 05:21:19 AM,...,102.0,29.0,409.0,27.0,5.0,N,N,N,N,chunk171.csv
8258,200114636,2020-01-11 23:24:22,INJURY,5,INJURY,5,01/11/2020 11:24:35 PM,Y,13,01/11/2020 11:24:48 PM,...,73.0,37.0,316.0,19.0,8.0,N,N,N,N,chunk165.csv
4754,201792124,2020-06-27 14:15:15,INJURY,5,INJURY,5,06/27/2020 02:15:46 PM,Y,31,06/27/2020 02:15:57 PM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk172.csv
3459,201293442,2020-05-08 22:46:18,OBMAJ,3,OBMAJ,3,05/08/2020 10:47:21 PM,Y,63,05/08/2020 10:48:05 PM,...,79.0,36.0,303.0,13.0,8.0,N,N,N,N,chunk170.csv
10631,201232831,2020-05-02 18:24:41,EDPC,7,EDPC,7,05/02/2020 06:25:15 PM,Y,34,05/02/2020 06:25:28 PM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk170.csv
7644,200990050,2020-04-08 00:13:40,ARREST,1,ARREST,1,04/08/2020 12:14:24 AM,Y,44,04/08/2020 12:14:33 AM,...,111.0,19.0,411.0,26.0,6.0,N,N,N,N,chunk169.csv
9083,200661839,2020-03-06 11:38:33,INJURY,5,INJURY,5,03/06/2020 11:38:45 AM,Y,12,03/06/2020 11:38:58 AM,...,103.0,27.0,412.0,28.0,5.0,N,N,N,N,chunk167.csv
10895,200935451,2020-04-02 19:55:51,DRUG,4,DRUG,4,04/02/2020 07:56:26 PM,Y,35,04/02/2020 07:56:33 PM,...,72.0,39.0,307.0,15.0,9.0,N,N,N,N,chunk169.csv
6725,201013033,2020-04-10 14:45:13,EDP,7,EDPC,7,04/10/2020 02:45:46 PM,Y,33,04/10/2020 02:45:52 PM,...,33.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk169.csv
12560,201752786,2020-06-23 17:18:18,SICK,6,SICK,6,06/23/2020 05:18:18 PM,Y,0,06/23/2020 05:18:18 PM,...,52.0,11.0,207.0,10.0,13.0,N,N,N,N,chunk172.csv
6170,200091726,2020-01-09 11:36:07,CARDBR,2,CARDBR,2,01/09/2020 11:36:14 AM,Y,7,01/09/2020 11:36:31 AM,...,49.0,13.0,211.0,11.0,14.0,N,N,N,N,chunk165.csv
10980,201013249,2020-04-10 15:33:15,INJURY,5,INJURY,5,04/10/2020 03:33:22 PM,Y,7,04/10/2020 03:33:39 PM,...,103.0,27.0,412.0,28.0,5.0,N,N,N,N,chunk169.csv
5903,200392208,2020-02-08 14:24:38,ABDPN,5,ABDPN,5,02/08/2020 02:24:48 PM,Y,10,02/08/2020 02:24:59 PM,...,102.0,28.0,409.0,27.0,5.0,N,N,N,N,chunk166.csv
10682,200482508,2020-02-17 15:16:52,SICK,6,SICK,6,02/17/2020 03:16:59 PM,Y,7,02/17/2020 03:17:26 PM,...,17.0,4.0,106.0,2.0,12.0,N,N,N,N,chunk167.csv
2573,201090013,2020-04-18 00:03:29,SICK,6,SICK,6,04/18/2020 12:04:11 AM,Y,42,04/18/2020 12:04:48 AM,...,34.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk170.csv

In [29]:
## get basic overview of the data
## what datatypes do the different columns hold?
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [31]:
## how many rows and columns are there
print ("columns = 32, rows = 13117")

columns = 32, rows = 13117

In [39]:
## Programmatically capture the 2245th FINAL_CALL_TYPE value and store in a variable.
target_finalcalltype = ems2020_excerpt_df["FINAL_CALL_TYPE"].iat[2245]
target_finalcalltype

'UNC'

In [61]:
# call an excel sheet 
cbp_df = pd.read_excel ("multi-data.xlsx", sheet_name = "CBP", skiprows = 6)

In [63]:
# call top 15
cbp_df. head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [66]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there 

cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [51]:
## how many rows and columns are there
print ("columns = 9, rows = 95721")

columns = 21, rows = 50140

In [68]:
# bottom 3
cbp_df. tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [70]:
# sample of 20
cbp_df. sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
34087,2017-10-18 04:40:00,2017-10-19 13:59:00,33.300000,1-2 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95206,2018-06-01 08:00:00,2018-06-05 11:08:00,99.133333,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
39644,2017-11-13 03:00:00,2017-11-15 07:11:00,52.166667,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2002,2017-01-25 19:40:00,2017-01-27 11:12:00,39.516667,Under 1 year,Female,HONDURAS,SBO,(b)(7)(E ),NaN
57575,2018-01-24 09:20:00,2018-01-25 08:53:00,23.533333,9-11 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
52160,2017-12-27 08:40:00,2017-12-30 07:11:00,70.500000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7429,2017-03-03 23:25:00,2017-03-04 11:14:00,11.800000,1-2 years,Male,ROMANIA,SBO,(b)(7)(E ),NaN
86754,2018-05-09 21:35:00,2018-05-14 10:31:00,108.916667,3-5 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
12641,2017-05-29 16:30:00,2017-05-30 09:07:00,16.600000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
80436,2018-04-21 20:33:00,2018-04-22 19:24:00,22.833333,15-18 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
93213,2018-05-26 18:30:00,2018-05-30 13:38:00,91.116667,3-5 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
60026,2018-02-03 23:54:00,2018-02-05 01:01:00,25.100000,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
12021,2017-05-22 16:40:00,2017-05-23 15:07:00,22.433333,12-14 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
11346,2017-05-12 22:47:00,2017-05-13 12:53:00,14.100000,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
17569,2017-07-12 23:45:00,2017-07-14 15:59:00,40.216667,12-14 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
20461,2017-08-01 06:00:00,2017-08-02 15:34:00,33.550000,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
67745,2018-03-10 19:20:00,2018-03-13 19:42:00,72.350000,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
3460,2017-01-31 14:00:00,2017-02-01 19:55:00,29.900000,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
20429,2017-08-01 01:15:00,2017-08-02 13:52:00,36.600000,1-2 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
89526,2018-05-17 20:10:00,2018-05-22 13:28:00,113.283333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN

In [74]:
# Programmatically capture the 8th hours_in_custody value and store in a variable.
target_hoursincustody = cbp_df["hours_in_custody"].iat[8]
target_hoursincustody

35.2666666666667